name: Node CI

on: workflow_dispatch

env:
  BIN_NAME: destreamer

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build
      run: |
        npm install
        npm run build
        npm install --global pkg
        pkg --output "build/$env:BIN_NAME" .
        cd build/
        Compress-Archive -Path "$env:BIN_NAME.exe" -DestinationPath "$env:BIN_NAME.zip"

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BIN_NAME }}-windows
        path: build/${{ env.BIN_NAME }}.zip

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build
      run: |
        npm install
        npm run build
        npm install --global pkg
        pkg --output "build/$BIN_NAME" .
        cd build/
        zip "$BIN_NAME.zip" "$BIN_NAME"

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BIN_NAME }}-macos
        path: build/${{ env.BIN_NAME }}.zip
